apiVersion: v1
kind: Secret
metadata:
  name: ddd-fast-api-secrets
  namespace: ddd-fast-api
type: Opaque
stringData:
  DDD_FAST_API_DATABASE_URL: postgresql+asyncpg://user:password@postgres.example:5432/ddd_fast_api
  DDD_FAST_API_AUTH_SECRET: replace-with-a-random-secret-at-least-16-characters
