apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddd-fast-api.fullname" . }}
  labels:
    {{- include "ddd-fast-api.labels" . | nindent 4 }}
data:
  DDD_FAST_API_APP_NAME: {{ .Values.config.appName | quote }}
  DDD_FAST_API_APP_ENV: {{ .Values.config.appEnv | quote }}
  DDD_FAST_API_APP_DEBUG: {{ .Values.config.appDebug | quote }}
  DDD_FAST_API_APP_LOG_LEVEL: {{ .Values.config.appLogLevel | quote }}
  DDD_FAST_API_CATALOG_REPOSITORY_BACKEND: {{ .Values.config.catalogRepositoryBackend | quote }}
  DDD_FAST_API_IDENTITY_REPOSITORY_BACKEND: {{ .Values.config.identityRepositoryBackend | quote }}
  DDD_FAST_API_AUTH_AUDIENCE: {{ .Values.config.authAudience | quote }}
  DDD_FAST_API_AUTH_TOKEN_TTL_SECONDS: {{ .Values.config.authTokenTtlSeconds | quote }}
  DDD_FAST_API_TELEMETRY_ENABLED: {{ .Values.config.telemetryEnabled | quote }}
  DDD_FAST_API_OUTBOUND_TIMEOUT_SECONDS: {{ .Values.config.outboundTimeoutSeconds | quote }}
  DDD_FAST_API_OUTBOUND_MAX_RETRIES: {{ .Values.config.outboundMaxRetries | quote }}
