apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ddd-fast-api

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

secretGenerator:
  - name: ddd-fast-api-secrets
    literals:
      - DDD_FAST_API_DATABASE_URL=postgresql+asyncpg://postgres:postgres@ddd-fast-api-postgres:5432/ddd_fast_api
      - DDD_FAST_API_AUTH_SECRET=local-development-secret-change-me

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/owezzy/ddd-fast-api
    newName: localhost:5001/ddd-fast-api
    newTag: dev

replicas:
  - name: ddd-fast-api
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: ddd-fast-api
    patch: |-
      - op: replace
        path: /data/DDD_FAST_API_APP_ENV
        value: development
      - op: replace
        path: /data/DDD_FAST_API_CATALOG_REPOSITORY_BACKEND
        value: memory
      - op: replace
        path: /data/DDD_FAST_API_IDENTITY_REPOSITORY_BACKEND
        value: memory
  - target:
      kind: PodDisruptionBudget
      name: ddd-fast-api
    patch: |-
      $patch: delete
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      metadata:
        name: ddd-fast-api
