apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ddd-fast-api

resources:
  - namespace.yaml
  - postgres.yaml

secretGenerator:
  - name: ddd-fast-api-postgres
    literals:
      - POSTGRES_DB=ddd_fast_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=__LOCAL_DEVELOPMENT_PASSWORD__

generatorOptions:
  disableNameSuffixHash: true
